In [2]:
import numpy as np

In [3]:
import array

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [6]:
 np.array([1,2,3,"as", 3.3])

array(['1', '2', '3', 'as', '3.3'], dtype='<U32')

In [7]:
np.array([2,3,4,5.0])

array([2., 3., 4., 5.])

In [9]:
np.array([[2,3], [5,6]])

array([[2, 3],
       [5, 6]])

In [10]:
np.array([[2,3], [5,6], [1,1,1,1]])

C:\Users\Tanjina\AppData\Local\Temp\ipykernel_13156\2507967733.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[2,3], [5,6], [1,1,1,1]])


array([list([2, 3]), list([5, 6]), list([1, 1, 1, 1])], dtype=object)

In [12]:
np.array([[[2,3], [5,6]], [[1,1],[1,1]]])

array([[[2, 3],
        [5, 6]],

       [[1, 1],
        [1, 1]]])

In [14]:
np.array([2,4,6], ndmin = 2)

array([[2, 4, 6]])

In [15]:
np.array([2,4,6], ndmin = 5)

array([[[[[2, 4, 6]]]]])

#  Mixed data Types

In [16]:
np.array([2,4,6], dtype = complex)

array([2.+0.j, 4.+0.j, 6.+0.j])

In [18]:
a = np.array([2,4], dtype = [("a",'complex'),("b",'int')])

In [19]:
a


array([(2.+0.j, 2), (4.+0.j, 4)], dtype=[('a', '<c16'), ('b', '<i4')])

In [26]:
a[0]

(2.+0.j, 2)

In [21]:
a[1][1]

4

In [23]:
type(a[1][0])

numpy.complex128

In [25]:
type(a[0][1])

numpy.int32

In [27]:
b = np.array([(2,4), (7,9)], dtype = [("a",'complex'),("b",'int')])

In [28]:
b

array([(2.+0.j, 4), (7.+0.j, 9)], dtype=[('a', '<c16'), ('b', '<i4')])

In [29]:
b[0]

(2.+0.j, 4)

In [30]:
type(b[1][0])

numpy.complex128

In [31]:
type(a[1][1])

numpy.int32

In [32]:
l = [3,5,78,9]

In [33]:
np.array(l)

array([ 3,  5, 78,  9])

In [34]:
np.asarray(l)

array([ 3,  5, 78,  9])

In [35]:
np.asanyarray(l)

array([ 3,  5, 78,  9])

In [38]:
issubclass(np.matrix, np.ndarray)

True

# Deep Copy vs Shallow Copy

In [59]:
arr = np.array([[2,3], [5,6], [8,9]])

In [60]:
arr

array([[2, 3],
       [5, 6],
       [8, 9]])

In [61]:
a = arr

In [62]:
b = np.copy(arr)

In [63]:
a 

array([[2, 3],
       [5, 6],
       [8, 9]])

In [64]:
b

array([[2, 3],
       [5, 6],
       [8, 9]])

In [65]:
arr[0][0]= 100

In [66]:
arr

array([[100,   3],
       [  5,   6],
       [  8,   9]])

In [71]:
# Shallow copy
a

array([[100,   3],
       [  5,   6],
       [  8,   9]])

In [73]:
# Deep copy
b

array([[2, 3],
       [5, 6],
       [8, 9]])

In [75]:
arr[0:1]

array([[100,   3]])

In [76]:
arr[0:2]

array([[100,   3],
       [  5,   6]])

In [77]:
arr[0:3]

array([[100,   3],
       [  5,   6],
       [  8,   9]])

In [78]:
arr[0:5]

array([[100,   3],
       [  5,   6],
       [  8,   9]])

In [79]:
arr[-1]

array([8, 9])

In [81]:
for i in arr:
     print(i)

[100   3]
[5 6]
[8 9]


# string to arr conv

In [83]:
np.fromstring("12 34 67 77 0", sep = ' ', dtype = int)

array([12, 34, 67, 77,  0])

In [86]:
a.ndim

2

In [87]:
a

array([[100,   3],
       [  5,   6],
       [  8,   9]])

In [88]:
a.shape


(3, 2)

In [89]:
a.size

6

In [90]:
a.dtype

dtype('int32')

# range

In [92]:
list(range(5))

[0, 1, 2, 3, 4]

In [93]:
np.arange(9,2, -2)

array([9, 7, 5, 3])

In [94]:
np.arange(3,12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
np.linspace(2,8)

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

# linspace

In [100]:
# generate 5 data in between 2 & 8 in equal spaces
np.linspace(2,8, 5)

array([2. , 3.5, 5. , 6.5, 8. ])

In [112]:
np.linspace(2,8, 5, endpoint=False)

array([2. , 3.2, 4.4, 5.6, 6.8])

# np.zeros()

In [101]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [104]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [105]:
np.zeros((4, 2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [107]:
np.ones((1,5,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [108]:
np.empty((3,3))

array([[4.67296746e-307, 1.69121096e-306, 1.33511018e-306],
       [7.56599807e-307, 1.42419938e-306, 7.56603881e-307],
       [8.45603440e-307, 4.45046008e-307, 2.37667058e-312]])

In [111]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [7]:
np.linspace(2,8,4, endpoint=False)

array([2. , 3.5, 5. , 6.5])

In [11]:
np.linspace([2,8],4, endpoint=False, axis = 1)

array([[2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96],
       [8.  , 7.92, 7.84, 7.76, 7.68, 7.6 , 7.52, 7.44, 7.36, 7.28, 7.2 ,
        7.12, 7.04, 6.96, 6.88, 6.8 , 6.72, 6.64, 6.56, 6.48, 6.4 , 6.32,
        6.24, 6.16, 6.08, 6.  , 5.92, 5.84, 5.76, 5.68, 5.6 , 5.52, 5.44,
        5.36, 5.28, 5.2 , 5.12, 5.04, 4.96, 4.88, 4.8 , 4.72, 4.64, 4.56,
        4.48, 4.4 , 4.32, 4.24, 4.16, 4.08]])

In [12]:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [13]:
np.logspace([2,3],4, axis = 1)

array([[  100.        ,   109.8541142 ,   120.67926406,   132.57113656,
          145.63484775,   159.98587196,   175.75106249,   193.06977289,
          212.09508879,   232.99518105,   255.95479227,   281.1768698 ,
          308.88435965,   339.32217719,   372.75937203,   409.49150624,
          449.8432669 ,   494.17133613,   542.86754393,   596.36233166,
          655.12855686,   719.685673  ,   790.60432109,   868.51137375,
          954.09547635,  1048.11313415,  1151.39539933,  1264.85521686,
         1389.49549437,  1526.41796718,  1676.83293681,  1842.06996933,
         2023.58964773,  2222.99648253,  2442.05309455,  2682.69579528,
         2947.05170255,  3237.45754282,  3556.48030622,  3906.93993705,
         4291.93426013,  4714.86636346,  5179.47467923,  5689.86602902,
         6250.55192527,  6866.48845004,  7543.12006335,  8286.42772855,
         9102.98177992, 10000.        ],
       [ 1000.        ,  1048.11313415,  1098.54114199,  1151.39539933,
         1206.79264064,

In [14]:
np.logspace([2],[3], axis = 1)

array([[ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
         120.67926406,  126.48552169,  132.57113656,  138.94954944,
         145.63484775,  152.64179672,  159.98587196,  167.68329368,
         175.75106249,  184.20699693,  193.06977289,  202.35896477,
         212.09508879,  222.29964825,  232.99518105,  244.20530945,
         255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
         308.88435965,  323.74575428,  339.32217719,  355.64803062,
         372.75937203,  390.69399371,  409.49150624,  429.19342601,
         449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
         542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
         655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
         790.60432109,  828.64277285,  868.51137375,  910.29817799,
         954.09547635, 1000.        ]])

In [15]:
d = np.linspace(1,9, 20)

In [16]:
d

array([1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053,
       3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368,
       5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684,
       7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ])

In [17]:
d.ndim

1

In [18]:
d.shape

(20,)

In [21]:
d.reshape(20,1)

array([[1.        ],
       [1.42105263],
       [1.84210526],
       [2.26315789],
       [2.68421053],
       [3.10526316],
       [3.52631579],
       [3.94736842],
       [4.36842105],
       [4.78947368],
       [5.21052632],
       [5.63157895],
       [6.05263158],
       [6.47368421],
       [6.89473684],
       [7.31578947],
       [7.73684211],
       [8.15789474],
       [8.57894737],
       [9.        ]])

In [28]:
d.reshape(2,2,5)

array([[[1.        , 1.42105263, 1.84210526, 2.26315789, 2.68421053],
        [3.10526316, 3.52631579, 3.94736842, 4.36842105, 4.78947368]],

       [[5.21052632, 5.63157895, 6.05263158, 6.47368421, 6.89473684],
        [7.31578947, 7.73684211, 8.15789474, 8.57894737, 9.        ]]])

In [30]:
np.random.rand(3)

array([0.2986943 , 0.81540259, 0.11192129])

In [31]:
np.random.randn(3)

array([-0.04137271, -0.49530116, -0.66190177])

In [33]:
np.random.rand(2,3)

array([[0.68089765, 0.45753143, 0.60317462],
       [0.75717146, 0.4375022 , 0.20076387]])

In [36]:
np.random.randint(2,13)

6

In [37]:
np.random.randint(2,13,(3,2))

array([[ 3,  9],
       [11,  2],
       [ 4,  2]])

In [38]:
a = np.random.randint(1,100, (5,5))

In [39]:
a

array([[61, 17, 70, 68, 76],
       [47, 46, 59, 80, 47],
       [86, 40, 72, 11, 50],
       [24, 64, 61, 59, 84],
       [98, 17, 58, 72, 98]])

In [40]:
a[3:, 3:]

array([[59, 84],
       [72, 98]])

In [41]:
a[:, 3]

array([68, 80, 11, 59, 72])

In [42]:
a[:, [1,3]]

array([[17, 68],
       [46, 80],
       [40, 11],
       [64, 59],
       [17, 72]])

In [43]:
a>40

array([[ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True, False,  True],
       [False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True]])

In [45]:
a[a>80]

array([86, 84, 98, 98])

# Element wise Multiplication

In [54]:
a1 = np.random.randint(1,4, (2,2))
a2 = np.random.randint(6,9, (2,2))

In [51]:
a1

array([[3, 3],
       [2, 2]])

In [57]:
a2

array([[7, 8],
       [7, 8]])

In [53]:
a1 * a2

array([[24, 18],
       [16, 12]])

# Matrix Multiplication

In [55]:
a1@a2

array([[21, 24],
       [28, 32]])

In [58]:
a3 =  np.random.randint(1,4, (2,4))

In [60]:
a3

array([[2, 3, 3, 1],
       [1, 3, 2, 3]])

In [62]:
a1@a3

array([[ 5,  9,  8,  5],
       [ 6, 12, 10,  8]])

In [63]:
a1**2

array([[4, 1],
       [4, 4]], dtype=int32)

In [67]:
b = np.zeros((2,3))

In [74]:
a = np.array([[1,2,3]])

In [75]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.]])

In [76]:
a

array([[1, 2, 3]])

In [77]:
a.T

array([[1],
       [2],
       [3]])

In [85]:
a4 =  np.random.randint(9,36, (2,3))

In [86]:
a4

array([[14, 34, 26],
       [20, 24, 33]])

In [87]:
np.sqrt(a4)

array([[3.74165739, 5.83095189, 5.09901951],
       [4.47213595, 4.89897949, 5.74456265]])

In [84]:
np.exp(a4)

array([[3.93133430e+12, 1.06864746e+13, 1.20260428e+06],
       [4.85165195e+08, 5.83461743e+14, 2.41549528e+07]])

# SEED

In [96]:
np.random.seed(30)
np.random.rand(2,3)

array([[0.64414354, 0.38074849, 0.66304791],
       [0.16365073, 0.96260781, 0.34666184]])